spring :
  datasource:
    url: jdbc:mysql://localhost:3306/testing
    username: root
    password: 1234
  jpa :
    show-sql: true
    hibernate :
      ddl-auto : update
logging:
  level:
    org.springframework.security: trace

cloudinary:
  cloud-name: dp7yogyps
  api-key: 571934253417438
  api-secret: yozTlFoNdn_dbKM9PuNi4aOhY2c

